### ISSUE TITLE
pip install -r leek/requirements.txt 报错，求助！！！

### ISSUE THREAD

**Issue by james007008** [mangege/leek#2]
运行 pip install -r leek/requirements.txt 报错
  Building wheel for accumulation-tree (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      D:\PythonProject\venv\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\accumulation_tree
      copying accumulation_tree\abctree.py -> build\lib.win-amd64-3.10\accumulation_tree
      copying accumulation_tree\treeslice.py -> build\lib.win-amd64-3.10\accumulation_tree
      copying accumulation_tree\__init__.py -> build\lib.win-amd64-3.10\accumulation_tree
      running build_ext
      c:\users\1\appdata\local\temp\pip-install-t5l8s9xr\accumulation-tree_ffb8db9fc61b4a5ba04776d3cbfeb216\.eggs\cython-0.29.32-py3.10.egg\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\1\AppData\Local\Temp\pip-install-t5l8s9xr\accumulation-tree_ffb8db9fc61b4a5ba04776d3cbfeb216\accumulation_tree\accumulation_tree.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\1\AppData\Local\Temp\pip-install-t5l8s9xr\accumulation-tree_ffb8db9fc61b4a5ba04776d3cbfeb216\setup.py", line 4, in <module>
          setup(
        File "D:\PythonProject\venv\lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "D:\PythonProject\venv\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "D:\PythonProject\venv\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "c:\users\1\appdata\local\temp\pip-install-t5l8s9xr\accumulation-tree_ffb8db9fc61b4a5ba04776d3cbfeb216\.eggs\cython-0.29.32-py3.10.egg\Cython\Distutils\old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
        File "c:\users\1\appdata\local\temp\pip-install-t5l8s9xr\accumulation-tree_ffb8db9fc61b4a5ba04776d3cbfeb216\.eggs\cython-0.29.32-py3.10.egg\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "D:\PythonProject\venv\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
          self.initialize()
        File "D:\PythonProject\venv\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "D:\PythonProject\venv\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "D:\PythonProject\venv\lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for accumulation-tree

**Comment by mangege** [comment]
accumulation-tree 依赖 c++ 编译环境,需要安装  Microsoft C++ Build Tools 

`setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

**Comment by mangege** [comment]
setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
